version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports: 
      - 9042:9042
    volumes:
      - ./app/cassandra:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - default
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra

  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    links:
      - cassandra
    networks:
      - default
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["tail", "-f", "/dev/null"]

volumes:
  cassandra:
    driver: local

networks:
  default:
    driver: bridge

